config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/show/:id', to: "welcome#show", as: :welcome_show
  root 'welcome#index'

  get 'files/:name', to: 'files#show', as: :file
  get 'files/', to: 'files#list', as: :files
  post 'files/', to: 'files#upload', as: :file_upload
  get 'files/download/:name', to: 'files#download', as: :file_download
  delete 'files/:name', to: 'files#remove', as: :filedelete

  get 'file_node_files/:name',
      to: 'file_node_files#show',
      as: :file_node_file
  get 'file_node_files/download/:name',
      to: 'file_node_files#download',
      as: :file_node_file_download
  get 'file_node_files/',
      to: 'file_node_files#list',
      as: :file_node_files
  post 'file_node_files/', to: 'file_node_files#upload', as: :file_node_upload
  delete 'file_node_files/:name', to: 'file_node_files#remove', as: :file_node_delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/file_node.rb
class FileNode < ApplicationRecord
  has_and_belongs_to_many :se_files
end

app/models/se_file.rb
class SeFile < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_and_belongs_to_many :file_nodes
  has_attached_file :attachment
  do_not_validate_attachment_file_type :attachment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/file_node_files_controller.rb
class FileNodeFilesController < ApplicationController
  protect_from_forgery with: :null_session
  def list
    if Rails.env.file_node?
      @file = SeFile.all
      render json: @file
    end
  end

  def show
    if Rails.env.file_node?
      @file = SeFile.find_by(name: params[:name])
      if @file.nil?
        render json: { message: "File #{params[:name]} not found" }, status: 400
      else
        render json: @file
      end
    end
  end

  def download
    if Rails.env.file_node?
      file = SeFile.find_by name: params[:name]
      if file.nil?
        render json: { message: "File #{params[:name]} not found" }, status: 400
      else
        send_file file.attachment.path
      end
    end
  end

  def remove
    successstr = "failure: File " + params[:name] + "does not exist in server database!"
    statusval = 400

    file = SeFile.find_by(name: params[:name])
    if file.nil?
      output = { :message => successstr }
      render :json => output, :status => statusval
      return
    end

    # Remove entry from database and delete file
    file.delete

    successstr = "success: File " + params[:name] + " successfully deleted!"
    statusval = 200

    # Respond with success appropriately
    output = { :message => successstr }
    render :json => output, :status => statusval
  end

  def post_params
    params.require(:se_file).permit(:name, :attachment)
  end

  def upload
    uploaded_file = SeFile.new post_params
    file_name = uploaded_file.name
    uploaded_file.save

    if post_params[:attachment].nil? || post_params[:attachment].size.zero?
      status_code = 400
      message = 'Upload failure: File attachment cannot be empty.'
    elsif post_params[:name].blank?
      status_code = 400
      message = 'Upload failure: Filename cannot be empty.'
    elsif !uploaded_file.errors.empty?
      status_code = 400
      message = uploaded_file.errors.full_messages
    else
      message = "Upload success: File #{file_name} successfully uploaded!"
      status_code = 200
    end

    render json: { message: message }, status: status_code
  end
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  protect_from_forgery with: :null_session
  def list
    @file = SeFile.all
    render :json => @file
  end

  def show
    @file = SeFile.find_by(name: params[:name])
     if @file.nil?
      render json: { message: "File #{params[:name]} not found" }, status: 400
    else
      render json: @file
    end
  end

  def download
    file = SeFile.find_by name: params[:name]
    if file.nil?
      render json: { message: "File #{params[:name]} not found" }, status: 400
    else
      node = FileNode.all.sample
      redirect_to "#{node.url}/file_node_files/download/#{file.name}"
      status_code = 200
    end
  end

  def remove
    successstr = "failure: File " + params[:name] + "does not exist in server database!"
    statusval = 400

    file = SeFile.find_by(name: params[:name])
    if file.nil?
      output = { :message => successstr }
      render :json => output, :status => statusval
      return
    end

    # Remove entry from database and delete file
    file.delete

    successstr = "success: File " + params[:name] + " successfully deleted!"
    statusval = 200

    # Respond with success appropriately
    system("~/replicateDB.sh")
    output = { :message => successstr }
    render :json => output, :status => statusval
  end

  def post_params
    params.require(:se_file).permit(:name, :attachment)
  end

  def upload
    uploaded_file = SeFile.new post_params
    file_name = uploaded_file.name
    uploaded_file.save

    if post_params[:attachment].nil? || post_params[:attachment].size.zero?
      status_code = 400
      message = 'Upload failure: File attachment cannot be empty.'
    elsif post_params[:name].blank?
      status_code = 400
      message = 'Upload failure: Filename cannot be empty.'
    elsif !uploaded_file.errors.empty?
      status_code = 400
      message = uploaded_file.errors.full_messages
    else
      FileNode.all.each do |node|
        url = node.url + '/files'
        RestClient.post(
          url,
          'se_file[name]' => file_name,
          'se_file[attachment]' => open(uploaded_file.attachment.path)
          system("~/replicateDB.sh")
        )
        node.se_files.append uploaded_file
      end
      message = "Upload success: File #{file_name} successfully uploaded!"
      status_code = 200
    end

    render json: { message: message }, status: status_code
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
def index
        @files = SeFile.all
        @newFile = SeFile.new
end

def show
    @file = SeFile.find(params[:id])
    #  if @file.nil?
    #   render json: { message: "File #{params[:id]} not found" }, status: 400
    # else
    #   render show.html.erb
    # end
end

def destroy
    successstr = "failure: File " + params[:name] + " does not exist in server database!" 
    statusval = 400

    file = SeFile.find_by(name: params[:name])
    if file.nil?
      output = { :message => successstr }
      render :json => output, :status => statusval
      return
    end

    # Remove entry from database and delete file
    file.delete

    successstr = "success: File " + params[:name] + " successfully deleted!"
    statusval = 200

    # Respond with success appropriately
    output = { :message => successstr }
    render :json => output, :status => statusval
  end
end

def create
  @file = SeFile.new(params[:name])
  puts params
  respond_to do |format|
    if @file.save
      flash[:notice] = 'File was successfully uploaded.'
      format.html { redirect_to(@file) }
      format.xml  { render :xml => @file, :status => :created,
	                :location => @file }
    else
      format.html { render :action => "new" }
      format.xml  { render :xml => @file.errors,
	                :status => :unprocessable_entity }
    end
  end
end

def download
    file = SeFile.find_by name: params[:name]
    if file.nil?
      render json: { message: "File #{params[:name]} not found" }, status: 400
    else
      send_file file.attachment.path
      flash[:notice] = 'File was successfully uploaded.'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_node_files_helper.rb
module FileNodeFilesHelper
end

app/helpers/files_helper.rb
module FilesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SeFilesystem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>

    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <!--<%= yield %>-->

    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<head>
    <meta charset="UTF-8">
    <title>Software Engineering</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
</head>
<style>

    ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background-color: #4aacf7;
        border: 0.5px solid black;
    }

    li {
        float: right;
    }

    li a {
        display: block;
        color: black;
        font-weight: bold;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
    }

    a:hover {
        color: white;
    }

    table, th, td{border-bottom: 1px solid black; border-collapse: collapse; margin: 5px; padding: 10px;}

    tr:hover {background-color: #C3C3C3;}

    button{cursor: pointer; text-decoration: none;}

    #uploadButton {
        background-color: white;
        border-radius: 5px;
        border:1px solid black;
        display:inline-block;
        color: black;
        font-size:14px;
        padding:10px 10px;
        margin: 10px;
    }

    #headerRow {color: white; text-shadow: 0 0 10px black; background-color: #4aacf7; border: 1px solid black;}
    #headerRow a:hover {cursor: pointer;}
    #headerRow:hover {background: 4aacf7;}

    a:hover{cursor: pointer;}

    .uploadArea {border: 1px solid black; margin: 3px; padding: 10px; border-radius: 10px; width: 30%;}


</style>

<%#
<button id="uploadButton" type="button">Upload</button>
%>
<table width="100%" style="margin: 0px;">
    <tr id="headerRow">
        <td><a>File Name</a></td>
        <td><a>Date Modified</a></td>
        <td>&nbsp</td>        
        <td>&nbsp</td>        
    </tr>

    <% @files.each do |file| %>
    
    <tr>
        <td><%= link_to file.name, welcome_show_url(file) %></td>
        <td><%= file.updated_at %></td>
        <td><%= link_to 'Download', file_download_url(:name => file.name) , :method => :get, :popup => true, :target => '_blank' %></td>
        <td><%= link_to 'Delete', filedelete_url(:name => file.name) , :method => :delete, :popup => true, :target => '_blank' %></td>      
    </tr>
    <% end %>

</table>
<br>
<div class="uploadArea">
<h3>Upload: </h3>

<%= form_for(@newFile, {:url => file_upload_url}) do |file| %>
  <p>
    <%= file.label :name %><br />
    <%= file.text_field :name %>
    <%= file.label :attachment %><br />
    <%= file.file_field :attachment %>

  </p>

  <p>
    <%= file.submit "Create" %>
  </p>
<% end %>
</div>

app/views/welcome/show.html.erb
    <div>
            <p>File Name: <%= @file.name %></p>
            <p>Date Modified: <%= @file.updated_at %> </p>     
    </div>
  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>